_target_: pdediff.nn.oned_unet.Unet
n_input_scalar_components: 1
n_input_vector_components: 0 
n_output_scalar_components: 1
n_output_vector_components: 0
hidden_channels: 128
ch_mults: [1, 1, 2, 4]
activation: 'GELU'
norm: true
n_dims: 2
use_scale_shift_norm: true
time_scale: 1000.0
padding_mode: "circular"
initial_block_multiplier: 2